model:
  obs_dim: 10
  action_dim: 2
  n_history: 1
  architecture: [96, 192, 192, 96]

plan:
  seed: 42
  n_actions: 10
  n_look_ahead: 1
  n_sample: 20000
  n_sample_chunk: 500
  noise_level: 1
  reward_weight: 500.0
